spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url : jdbc:mysql://metavers.ohgiraffers.com:3306/menu (??)
    url : jdbc:mysql://localhost:3306/menu #?? #??ip?? :127.0.0.1
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
      #create: ??? ?? ?? mapping ?????? ???? ddl?? ????. ??? ????? ?? ??.
      #create-drop: ?? ???? ??? ??? ????
      # none? ddl ????, ???? none?? ???? ??? ????
      # update? ??? ???? ??? ??
      # validate ??? ??? ?? ?? (?? ?????)
    properties:
      hibernate:
        format_sql: true